account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(template_name='account/signup.html'), name='회원가입'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.sign, name='sign'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('id_search/', views.RecoveryIdView.as_view(), name='id_search'),
    path('id_search/find/', views.ajax_find_id_view, name='ajax_id'),
    path('pw_search/', views.RecoveryPwView.as_view(), name='pw_search'),
    path('recovery/pw/find/', views.ajax_find_pw_view, name='ajax_pw'),
    path('recovery/pw/auth/', views.auth_confirm_view, name='recovery_auth'),
    path('recovery/pw/reset/', views.auth_pw_reset_view, name='pw_reset'),
    path('registerauth/', views.register_success, name='register_success'),
    path('activate/<str:uid64>/<str:token>/', views.activate, name='activate'),
]

bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('', views.index, name='index'),
    path('write.html', views.m_new, name='m_new'),
    path('list.html', views.list, name='list'),
    path('<int:pk>/', views.detail, name='detail'),
    path('edit/<int:pk>', views.edit, name='edit' ),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('chat/', views.chati, name='chati'),
    path('<str:room_name>/', views.room, name='room'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
# from bbs.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bbs.urls')),
    path('account/', include('account.urls')),
    path('chat/', include('chat.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
        rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/quill/quill.snow.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/quill/quill.bubble.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/simple-datatables/style.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    {% include 'header.html' %}
    {% block content %}{% endblock %}
</body>

</html>

templates/header.html
  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center" >

    <div class="d-flex align-items-center justify-content-between">
      <a href="/" class="logo d-flex align-items-center">
        <img src="/img/logo.png" alt="">
        <span class="d-none d-lg-block">Admin</span>
      </a>
      <!-- <i class="bi bi-list toggle-sidebar-btn"></i> -->
    </div><!-- End Logo -->

    <div class="offcanvas-body p-4 pt-0 p-lg-0">
        <hr class="d-lg-none text-white-50">
        <ul class="navbar-nav flex-row flex-wrap bd-navbar-nav">
          <li class="nav-item col-6 col-lg-auto">
            <a class="nav-link py-2 px-0 px-lg-2" href="{% url 'bbs:list' %}">게시판</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item col-6 col-lg-auto">
            <a href="{% url 'account:logout' %}" class="btn btn-alert">로그아웃</a>
          </li>
          <li class="nav-item col-6 col-lg-auto">
            <a href="{% url 'chat:chati' %}" class="btn btn-alert">채팅</a>
          </li>
          {% else %}
          <li class="nav-item col-6 col-lg-auto">
            <a href="{% url 'account:sign' %}" class="btn btn-alert">회원가입</a>
          </li>
          <li class="nav-item col-6 col-lg-auto">
            <a href="{% url 'account:login' %}" class="btn btn-alert">로그인</a>
          </li>
          <li class="nav-item col-6 col-lg-auto">
            <a href="{% url 'account:id_search' %}" class="btn btn-alert">아이디 찾기</a>
          </li>
          <li class="nav-item col-6 col-lg-auto">
            <a href="{% url 'account:pw_search' %}" class="btn btn-alert">비밀번호 찾기</a>
          </li>
          {% endif %}
          <li class="nav-item col-6 col-lg-auto">
            <a href="{% url 'admin:index' %}" class="btn btn-alert">관리자</a>
          </li>
        </ul>
    </div>

  </header><!-- End Header -->

templates/index.html
{% extends 'base.html' %}
{% block title %}메인{% endblock %}
{% block content %}
    메인입니다.
{% endblock %}