bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'

urlpatterns = [
    path('', views.index, name='index'),
    path('write.html', views.m_new, name='m_new'),
    path('list.html', views.list, name='list'),
    path('<int:pk>/', views.detail, name='detail'),
    path('edit/<int:pk>', views.edit, name='edit' ),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
# from bbs.views import *
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bbs.urls')),
    path('account/', include('account.urls')),
    path('chat/', include('chat.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

bbs/models.py
from django.db import models
# from account.models import User
from django.conf import settings


# Create your models here.
class Board(models.Model):
    seq = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, null=False)
    title = models.CharField(max_length=50, null=False)
    contents = models.TextField(null=False)
    url = models.URLField(null=False)
    email = models.EmailField(null=False)
    cdate = models.DateTimeField(auto_now_add=True)
    user_id = models.CharField(max_length=50, null=True)           # settings.AUTH_USER_MODEL, db_column='user_id', on_delete=models.DO_NOTHING, 

    def __str__(self):
        return self.name 
    
    

bbs/forms.py
from django import forms
from bbs.models import *

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields=['name', 'title', 'contents', 'url', 'email']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 100%;',
                'placeholder': '이름',
                'label': "이름"
            }),
            'title': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 100%;',
                'placeholder': '제목'
            }),
            'contents': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 100%;height:300px',
                'placeholder': '내용'
            }),
            'url': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 100%;',
                'placeholder': 'Url'
            }),
            'email': forms.TextInput(attrs={
                'class': "form-control",
                'style': 'max-width: 100%;',
                'placeholder': 'Email'
            }),
        }

bbs/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .forms import BoardForm
from .models import Board

# Create your views here.
def index(request):
    return render(request, 'index.html')

def m_new(request):
    # print(request.user.user_id)
    # 글등록시
    if request.method == 'POST':
        form = BoardForm(request.POST)
        # if form.is_valid():
        #     form.save()
        if form.is_valid():
            BBS = form.save(commit=False)
            BBS.user_id = request.user.user_id
            BBS.save()

        return redirect('bbs:list') 
    
    # 페이지 그냥 들어온경우
    else:
        form = BoardForm()
    return render(request, 'bbs/write.html', {'forms':form})


def list(request):
    articleList = Board.objects.all()
    return render(request, 'bbs/list.html', {'articleList':articleList})


def detail(request, pk):
    article = Board.objects.get(seq=pk)
    return render(request, 'bbs/view.html', {'article':article})

def edit(request, pk):
    edit = Board.objects.get(seq=pk)
    return render(request, 'bbs/edit.html', {'Board':edit})

def update(request, pk):
    # update_Board = Board.objects.get(id=pk)
    # update_Board.title = request.POST['title']
    # update_Board.name = request.POST['writer']
    # update_Board.contents = request.POST['body']
    # # update_Board.pub_date = timezone.now()
    # update_Board.save()
    form = get_object_or_404(Board, seq=pk)
    BBS = BoardForm(request.POST, instance=form)
    if BBS.is_valid():
        aaa = BBS.save(commit=False)
        aaa.save()

    return redirect('bbs:edit', pk=pk )

def delete(request, pk):
    delete_Board = Board.objects.get(id=pk)
    delete_Board.delete()

    return redirect('bbs:list')

def ati(request):
    # print(request.user_id)
    return render(request,'bbs/list.html')

templates/bbs/edit.html
{% extends 'base.html' %}
{% block title %}수정{% endblock %}
{% block content %}
    <form action="{% url 'bbs:update' Board.seq %}" method="POST">
        {% csrf_token %}
        <!-- <input type="hidden" name="id" value="{{Board.id}}"><br> -->
        <div class="container text-center fluid pt-3">
        <form>
          <div class="row g-5">
            <div class="input-group pb-md-3">
              <span class="input-group-text w-25">제목</span>
              <input type="text" name="title" id="titlle" value="{{Board.title}}" class="form-control">
            </div>
          </div>  
          <div class="row g-3">
            <div class="input-group pb-md-3">
              <span class="input-group-text w-25">저자</span>
              <input type="text" name="name" id="name" value="{{Board.name}}" class="form-control">
            </div>
          </div>  
          <div class="row g-3">
            <div class="input-group pb-md-3">
              <span class="input-group-text w-25">내용</span>
              <textarea name="contents" id="contents" cols="20" rows="10" class="form-control">{{Board.contents}}</textarea>
            </div>
          </div>  
          <div class="row g-3">
            <div class="input-group pb-md-3">
              <span class="input-group-text w-25">Url</span>
              <input type="url" name="url" maxlength="200" value="{{Board.url}}" class="form-control">
            </div>
          </div>  
          <div class="row g-3">
            <div class="input-group pb-md-3">
                <span class="input-group-text w-25">Email</span>
                <input type="email" name="email" maxlength="254" value="{{Board.email}}" class="form-control">
            </div>
          </div>  
          <div class="row g-3">
            <div class="text-start col-6">
              <button type="submit" class="btn btn-primary">제출</button>
            </div>
            <div class="text-end col-6">
              <a href="{% url 'bbs:list' %}"><span class="btn btn-primary">목록</span></a>
            </div>
          <div class="row g-3">
        </div>
        </form><!-- Vertical Form -->

        <!-- <label for="title">제목</label>
        <input type="text" name="title" id="titlle" value="{{Board.title}}">
        <br>
        <label for="writer">저자</label>
        <input type="text" name="name" id="name" value="{{Board.name}}" >
        <br>
        <label for="body">내용</label>
        <textarea name="contents" id="contents" cols="30" rows="10">{{Board.contents}}</textarea>
        <p>
            <label for="id_url">Url</label>
            <input type="url" name="url" maxlength="200" value="{{Board.url}}">
        </p>
        <p>
            <label for="id_email">Email:</label>
            <input type="email" name="email" maxlength="254" value="{{Board.email}}">
        </p> -->
        <!-- <button type="submit">제출</button> | 
        <a href="{% url 'bbs:list' %}">목록</a> -->
    </form>
{% endblock %}

templates/bbs/list.html
{% extends 'base.html' %}
{% block title %}목록{% endblock %}
{% block content %}
    <div class="container-fluid pt-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">타이틀</h5>

                <!-- Default Table -->
                <table class="table">
                    <thead>
                        <tr>
                            <th class="col-1">#</th>
                            <th class="col-2">저자</th>
                            <th class="col-7">제목</th>
                            <th class="col-2">날짜</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for article in articleList %}
                        <tr>
                            <th>{{ forloop.counter }}</th>
                            <td>{{article.name}}</td>
                            <td><a href="{% url 'bbs:detail' article.seq %}">{{ article.title }}</a></td>
                            <td>{{ article.cdate|date:"Y-m-d H:i:s" }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <!-- End Default Table Example -->
            </div>
        </div>
        <!-- <button class="btn btn-primary">등록</button> -->
        <div style='width: 100px; float:right'>
            {% if request.user.is_authenticated %}
            <a href="{% url 'bbs:m_new' %}"><span class="btn btn-primary">등록</span></a>
            {% else %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/bbs/view.html
{% extends 'base.html' %}
{% block title %}뷰{% endblock %}
{% block content %}
    <div class="card fluid pt-3 h-100">
        <div class="card-body">

            <!-- Dark Table -->
            <div class="container text-center fluid">
            <table class="table table-light h-75">
                <tbody>
                    <tr>
                        <td class="col-2 text-end border-end">제목</td>
                        <td class="col-10">{{ article.title }}</td>
                    </tr>
                    <tr>
                        <td class="text-end border-end">저 자</td>
                        <td>{{ article.name }}</td>
                    </tr>
                    <tr>
                        <td class="text-end border-end h-100">내 용</td>
                        <td>{{ article.contents }}</td>
                    </tr>
                    <tr>
                        <td class="text-end border-end">이메일</td>
                        <td>{{ article.email }}</td>
                    </tr>
                </tbody>
            </table>
            <!-- End Dark Table -->
            <div>
            {% if user.get_username == article.user_id %}
                <a href="{% url 'bbs:edit' article.seq %}"><span class="btn btn-outline-primary">수정</span></a>
                <a href="{% url 'bbs:delete' article.seq %}"><span class="btn btn-outline-primary">삭제</span></a>
            {% endif %}
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/bbs/write.html
{% extends 'base.html' %}
{% block title %}등록{% endblock %}
{% block content %}

<div class="card-body">
    <div class="card-body pt-3">
        <!-- Floating Labels Form -->
        <form method="POST">
            {% csrf_token %}
            <div class="form-floating col-md-12 m-sm-1">
                {{forms.name}}
                <label for="floatingInput">이름</label>
            </div>
            <div class="col-md-12 m-sm-1">
                {{forms.title}}
            </div>
            <div class="col-md-12 m-sm-1">
                {{forms.contents}}
            </div>
            <div class="col-md-12 m-sm-1">
                {{forms.url}}
            </div>
            <div class="col-md-12 m-sm-1">
                {{forms.email}}
            </div>
            <div class="col-md-12 m-sm-1">
                <div class="text-center">
                    <button type="submit" class="btn btn-Info rounded-pill">저장</button>
                </div>
            </div><!-- <button type="submit" class="btn btn-primary">저장</button> -->
        </form><!-- End floating Labels Form -->
    </div>
</div>
{% endblock %}